from res import RESOURCES_DIR

MARIO_WIDTH = 22
MARIO_HEIGHT = 30
MARIO_SPEED = 20
MARIO_JUMP_POWER = 50
DEAD_MARIO_LEN = 500
GRAVITATION = 2.5

BUMP_MOVE = 25
BUMP_MAX_LEN = 500
BUMP_WIDTH = 10

FIRE_MOVE = 10
FIRE_MAX_LEN = 50

FLY_DEATH_XMOVE = 15
FLY_DEATH_YMOVE = 10
FLY_DEATH_MAX_LEN = 100
FLY_DEATH_MAX_HEIGHT = 50

ANIMATED_LEFT = f"{RESOURCES_DIR}/heros/left.png"
ANIMATED_LEFT2 = f"{RESOURCES_DIR}/heros/left2.png"

ANIMATED_RIGHT = f"{RESOURCES_DIR}/heros/right.png"
ANIMATED_RIGHT2 = f"{RESOURCES_DIR}/heros/right2.png"

ANIMATED_STATE = f"{RESOURCES_DIR}/heros/0.png"
ANIMATED_JUMP = f"{RESOURCES_DIR}/heros/jump.png"
ANIMATED_LJUMP = f"{RESOURCES_DIR}/heros/jump_left.png"
ANIMATED_RJUMP = f"{RESOURCES_DIR}/heros/jump_right.png"
ANIMATED_DIE = f"{RESOURCES_DIR}/heros/die.png"
